package com.ygl.test.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ygl.test.greendao.entity.Data;
import com.ygl.test.greendao.entity.ImageEntity;

import com.ygl.test.greendao.dao.DataDao;
import com.ygl.test.greendao.dao.ImageEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDaoConfig;
    private final DaoConfig imageEntityDaoConfig;

    private final DataDao dataDao;
    private final ImageEntityDao imageEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDaoConfig = daoConfigMap.get(DataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        imageEntityDaoConfig = daoConfigMap.get(ImageEntityDao.class).clone();
        imageEntityDaoConfig.initIdentityScope(type);

        dataDao = new DataDao(dataDaoConfig, this);
        imageEntityDao = new ImageEntityDao(imageEntityDaoConfig, this);

        registerDao(Data.class, dataDao);
        registerDao(ImageEntity.class, imageEntityDao);
    }
    
    public void clear() {
        dataDaoConfig.clearIdentityScope();
        imageEntityDaoConfig.clearIdentityScope();
    }

    public DataDao getDataDao() {
        return dataDao;
    }

    public ImageEntityDao getImageEntityDao() {
        return imageEntityDao;
    }

}
